// Generates supabase/seed.sql from the canonical app seed data so the database
// never drifts from the frontend. Re-run after editing src/data/worldCup2026.ts:
//
//   node supabase/generate-seed.mjs
//
// The output is idempotent (upserts) and references members by member_key, so
// selections survive even though member ids are generated uuids.
import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const { teams, fixtures, demoMembers, demoSelections, defaultRules } = await import(
  path.join(here, '..', 'src', 'data', 'worldCup2026.ts')
)

const q = (value) => (value === null || value === undefined ? 'null' : `'${String(value).replace(/'/g, "''")}'`)
const jsonLiteral = (value) => `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`

const lines = []
lines.push('-- AUTO-GENERATED by supabase/generate-seed.mjs. Do not edit by hand.')
lines.push('-- Run supabase/schema.sql first, then this file.')
lines.push('begin;')
lines.push('')

lines.push('-- Teams (48)')
for (const t of teams) {
  lines.push(
    `insert into public.teams (id, group_code, name, short_name, flag_code, confederation, seed) values ` +
      `(${q(t.id)}, ${q(t.group)}, ${q(t.name)}, ${q(t.shortName)}, ${q(t.flag)}, ${q(t.confederation)}, ${t.seed}) ` +
      `on conflict (id) do update set group_code = excluded.group_code, name = excluded.name, short_name = excluded.short_name, flag_code = excluded.flag_code, confederation = excluded.confederation, seed = excluded.seed;`,
  )
}
lines.push('')

lines.push(`-- Fixtures (${fixtures.length})`)
for (const f of fixtures) {
  lines.push(
    `insert into public.fixtures (id, group_code, match_date, venue, home_team_id, away_team_id) values ` +
      `(${q(f.id)}, ${q(f.group)}, ${q(f.date)}, ${q(f.venue)}, ${q(f.homeTeamId)}, ${q(f.awayTeamId)}) ` +
      `on conflict (id) do update set group_code = excluded.group_code, match_date = excluded.match_date, venue = excluded.venue, home_team_id = excluded.home_team_id, away_team_id = excluded.away_team_id;`,
  )
}
lines.push('')

lines.push(`-- Members (${demoMembers.length})`)
for (const m of demoMembers) {
  lines.push(
    `insert into public.members (member_key, real_name, line_display_name) values ` +
      `(${q(m.id)}, ${q(m.name)}, ${q(m.lineName)}) ` +
      `on conflict (member_key) do update set real_name = excluded.real_name, line_display_name = excluded.line_display_name;`,
  )
}
lines.push('')

lines.push(`-- Selections (${demoSelections.length}) referencing members by member_key`)
const slotByTeam = new Map()
for (const s of demoSelections) {
  const slot = (slotByTeam.get(s.teamId) || 0) + 1
  slotByTeam.set(s.teamId, slot)
  lines.push(
    `insert into public.selections (member_id, team_id, owner_slot) ` +
      `select id, ${q(s.teamId)}, ${slot} from public.members where member_key = ${q(s.memberId)} ` +
      `on conflict (member_id, team_id) do nothing;`,
  )
}
lines.push('')

lines.push('-- Default ruleset (2022 previous-tournament rules)')
lines.push(
  `insert into public.rulesets (id, rules, awards) values ('default', ${jsonLiteral(defaultRules)}, '{}'::jsonb) ` +
    `on conflict (id) do update set rules = excluded.rules;`,
)
lines.push('')
lines.push('commit;')
lines.push('')

await writeFile(path.join(here, 'seed.sql'), lines.join('\n'), 'utf8')
console.log(`seed.sql written: ${teams.length} teams, ${fixtures.length} fixtures, ${demoMembers.length} members, ${demoSelections.length} selections`)
