// Parse the user's Japanese 2026 World Cup squad PDF (text-extracted) into
// structured data: per-country summary + coach, and full katakana squads with
// clubs. Run pdftotext first, then this:
//
//   pdftotext -layout "<the PDF>" /tmp/wcsquads.txt
//   node scripts/build-wc-pdf.mjs /tmp/wcsquads.txt
//
// Writes src/data/wcPdf.ts (committed). Only factual data (names/clubs/coach
// and a short country summary) is extracted.
import { readFileSync } from 'node:fs'
import { writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(here, '..')
const { teamNamesJa } = await import(path.join(root, 'src', 'data', 'worldCup2026.ts'))

const nameToId = {}
for (const [id, ja] of Object.entries(teamNamesJa)) nameToId[ja] = id
Object.assign(nameToId, {
  チェコ共和国: 'czechia',
  アメリカ合衆国: 'usa',
  七面鳥: 'turkiye',
  コンゴ民主共和国: 'dr-congo',
})

const srcPath = process.argv[2] || '/tmp/wcsquads.txt'
const lines = readFileSync(srcPath, 'utf8').split('\n').map((l) => l.replace(/\s+$/, ''))

const POS = [
  { re: /^(ゴールキーパー|ＧＫ|GK)\s*[：:]/, pos: 'GK' },
  { re: /^(ディフェンダー|ＤＦ|DF)\s*[：:]/, pos: 'DF' },
  { re: /^ミッドフィールダーとフォワード\s*[：:]/, pos: 'MF' },
  { re: /^(ミッドフィールダー|ＭＦ|MF)\s*[：:]/, pos: 'MF' },
  { re: /^(フォワード|ＦＷ|FW)\s*[：:]/, pos: 'FW' },
]
const isCoach = (l) => /^(監督|コーチ)\s*[：:]/.test(l)
const isCaption = (l) => /ゲッティ|イメージ|ロイター|通信|（写真|画像提供/.test(l)
const isGroup = (l) => /^グループ/.test(l)
const posOf = (l) => POS.find((p) => p.re.test(l))
const narrativeLeakRe = /代表|メンバー|ワールドカップ|開催|選出|監督|チーム|グループ|写真|Getty|AFP|ゲッティ|ロイター|通信|ディフェンダー|ミッドフィールダー|フォワード|ゴールキーパー|ストライカー/

function cleanClub(value) {
  if (!value) return undefined
  const club = value.replace(/｡.*/, '').trim()
  if (!club || narrativeLeakRe.test(club) || /の.+が$/.test(club)) return undefined
  return club
}

function shouldSkipPlayerEntry(name, club) {
  if (!name) return true
  if (narrativeLeakRe.test(name)) return true
  if (/^[。、､，,.]+$/.test(name)) return true
  if ((club || '').length > 0 && narrativeLeakRe.test(club)) return true
  return false
}

const info = {} // id -> { summary, coach }
const squads = {} // id -> [{name,pos,club}]

let team = null
let mode = null // 'narrative' | 'pos'
let narrative = []
let curPos = null
let posBuf = []

function flushPos() {
  if (!team || !curPos || posBuf.length === 0) {
    curPos = null
    posBuf = []
    return
  }
  const joined = posBuf.join('')
  for (let entry of joined.split(/[､、,，]/)) {
    entry = entry.trim()
    if (!entry) continue
    let name = entry
    let club
    const paren = entry.match(/[(（]\s*([^)）]+?)\s*[)）]/)
    if (paren) {
      club = paren[1].trim()
      name = entry.slice(0, entry.search(/[(（]/)).trim()
    } else {
      const m = entry.match(/^(\S+?)[ 　]+(.+)$/)
      if (m) {
        name = m[1].trim()
        club = m[2].trim()
      }
    }
    name = name.replace(/[（）()]/g, '').trim()
    club = cleanClub(club)
    if (!shouldSkipPlayerEntry(name, club)) (squads[team] = squads[team] || []).push({ name, pos: curPos, club })
  }
  curPos = null
  posBuf = []
}

function flushNarrative() {
  if (team && narrative.length) {
    info[team] = info[team] || {}
    info[team].summary = narrative.join('').trim()
  }
  narrative = []
}

for (const raw of lines) {
  const line = raw.trim()
  if (nameToId[line]) {
    flushPos()
    flushNarrative()
    team = nameToId[line]
    mode = 'narrative'
    info[team] = info[team] || {}
    continue
  }
  if (!team) continue
  if (isGroup(line)) {
    flushPos()
    flushNarrative()
    continue
  }
  if (isCoach(line)) {
    flushPos()
    flushNarrative()
    info[team].coach = line.replace(/^(監督|コーチ)[：:]\s*/, '').trim()
    mode = null
    continue
  }
  const p = posOf(line)
  if (p) {
    flushPos()
    flushNarrative()
    curPos = p.pos
    posBuf = [line.replace(p.re, '')]
    mode = 'pos'
    continue
  }
  if (mode === 'pos') {
    if (line === '' || isCaption(line)) {
      flushPos()
      mode = null
      continue
    }
    posBuf.push(line)
    continue
  }
  if (mode === 'narrative') {
    if (line === '' || isCaption(line)) continue
    narrative.push(line)
  }
}
flushPos()
flushNarrative()

const ts =
  `// AUTO-GENERATED by scripts/build-wc-pdf.mjs from the user's 2026 WC squad PDF.\n` +
  `export type PdfPlayer = { name: string; pos: 'GK' | 'DF' | 'MF' | 'FW'; club?: string }\n` +
  `export const pdfCountryInfo: Record<string, { summary: string; coach?: string }> = ${JSON.stringify(info, null, 2)}\n` +
  `export const pdfSquads: Record<string, PdfPlayer[]> = ${JSON.stringify(squads, null, 2)}\n`

await writeFile(path.join(root, 'src', 'data', 'wcPdf.ts'), ts, 'utf8')
const teamsParsed = Object.keys(squads).length
const totalPlayers = Object.values(squads).reduce((a, b) => a + b.length, 0)
const withInfo = Object.values(info).filter((i) => i.summary).length
console.log(`wcPdf.ts: ${teamsParsed} teams, ${totalPlayers} players, ${withInfo} summaries`)
